Agent: REINFORC

Env:
  name: CartPole-v0
  state_size: 4
  action_size: 2

DQN:
  episodes: 100
  sync_interval: 10
  gamma: 0.98
  lr: 0.001
  epsilon: 0.1
  batch_size: 64
  buffer_size: 10000
  loss_function: L1smooth

REINFORCE:
  episodes: 100
  gamma: 0.98
  lr: 0.001

ActorCritic:
  episodes: 100
  gamma: 0.98
  pl_net_lr: 0.001
  v_net_lr: 0.001
  loss_function: L1smooth